### ISSUE TITLE
Getting Null pointer Exception on image's getGray while calculating difference between two images

### ISSUE THREAD

**Issue by deepsidhu1313** [DiegoCatalano/Catalano-Framework#27]
Hi,

I am newbie to image processing and i am using this framework for first time.

I am getting null pointer exception when your code try to access gray of the image
`Exception in thread "main" java.lang.NullPointerException
	at Catalano.Imaging.FastBitmap.getGray(FastBitmap.java:942)
	at Catalano.Imaging.Tools.ObjectiveFidelity.getMSE(ObjectiveFidelity.java:122)
	at qualityanalysis.QualityAnalysis.calculate(QualityAnalysis.java:44)
	at qualityanalysis.QualityAnalysis.main(QualityAnalysis.java:105)`

I am using simple code mentioned [here](https://stackoverflow.com/questions/21179019/how-to-compare-set-of-images-in-java-using-pixel-based-image-comparision-metric) in the answer.

**Comment by deepsidhu1313** [comment]
Sorry got the answer in the comment below. Thanks :). BTW isn't there anything which converts the image automatically while comparing, like

`if(!isGrayscale() || getGraydata==null){
this.toGrayscale()
}` 

because you are comparing gray to compute the error.
