### ISSUE TITLE
DrawLine inverts X and Y coordinates

### ISSUE THREAD

**Issue by claudiocantalupo-spotsoftware** [DiegoCatalano/Catalano-Framework#7]
- Catalano Framework: 1.4
- Android 4.4.4

Hello Diego,
if i run this sample code:
```java
FastGraphics graph = new FastGraphics(image);
graph.setColor(180, 255, 50);
graph.DrawLine(new IntPoint(10, 10), new IntPoint(10, 110));
_imgView.setImageBitmap(image.toBitmap());
```

I expect a vertical line to be drawn but an horizontal one is drawn instead (is IntPoint(x, y) right?)

I have another issue, maybe related to the above mentioned (major issues in the pixel coordinate management?), if I call the DrawCircle this way:
```java
_graph.DrawCircle(new IntPoint(269, 15), 5)
```

I got this exception:
_java.lang.ArrayIndexOutOfBoundsException: length=76800; index=87695
            at Catalano.Imaging.FastBitmap.setRGB(FastBitmap.java:438)
            at Catalano.Imaging.FastGraphics.DrawCircle(FastGraphics.java:97)
            at Catalano.Imaging.FastGraphics.DrawCircle(FastGraphics.java:81)_

The frame size is 320 x 240 (width x height) so, theoretically I should be able to draw a 5 pixels radius circle at 269,15 (x,y).

Anyway, thank you for this great framework.
Claudio

**Comment by claudiocantalupo-spotsoftware** [comment]
Sorry, I just noticed this closed issue #1.

No more explanation is needed but I think that the html documentation is a little bit misleading:
_(from the original javadoc of IntPoint class):
Constructor and Description 
IntPoint(double x, double y) 
Initializes a new instance of the IntPoint class._
